=== Adrisito123/LMSGI/UD4/Actividad6/modulos.dtd
<!ELEMENT modulos (modulo+)>
<!ELEMENT modulo (contenidos)>
<!ATTLIST modulo nombre CDATA #REQUIRED>
<!ELEMENT contenidos (ud+)>
<!ELEMENT ud (tipo, descripcion)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

=== Adrisito123/LMSGI/UD4/Actividad6/modulos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modulos SYSTEM "modulos.dtd">
<modulos>
    <modulo nombre="Entornos de Desarrollo">
        <contenidos>
            <ud>
                <tipo>Teorico</tipo>
                <descripcion>Base teorica sobre git y su entorno</descripcion>
            </ud>
            <ud>
                <tipo>Practico</tipo>
                <descripcion>Taller practico de git</descripcion>
            </ud>
        </contenidos>
    </modulo>
    <modulo nombre="Programacion">
        <contenidos>
            <ud>
                <tipo>Teorico</tipo>
                <descripcion>Base sobre que es la programacion</descripcion>
            </ud>
            <ud>
                <tipo>Practico</tipo>
                <descripcion>Iniciando java</descripcion>
            </ud>
        </contenidos>
    </modulo>
</modulos>
