=== Adrisito123/LMSGI/UD4/Actividad4/Actividad1.dtd
<!ELEMENT gestoria (sede)>
<!ELEMENT sede (codigoSede, nombreEmpleado, fechaAlta, clientes)>
<!ELEMENT codigoSede (#PCDATA)>
<!ELEMENT nombreEmpleado (#PCDATA)>
<!ELEMENT fechaAlta (#PCDATA)>
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (codigoCliente, descripcionCliente, numeroVivienda, costeVivienda, resumenViviendas, plazoAltaHacienda)>
<!ELEMENT codigoCliente (#PCDATA)>
<!ELEMENT descripcionCliente (#PCDATA)>
<!ELEMENT numeroVivienda (#PCDATA)>
<!ELEMENT costeVivienda (#PCDATA)>
<!ELEMENT resumenViviendas (#PCDATA)>
<!ELEMENT plazoAltaHacienda (#PCDATA)>

=== Adrisito123/LMSGI/UD4/Actividad4/Actividad3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gestoria SYSTEM "Actividad1.dtd">
<gestoria>
  <sede>
    <codigoSede>A9876543</codigoSede>
    <nombreEmpleado>Carlos Rodríguez</nombreEmpleado>
    <fechaAlta>10-11-2023</fechaAlta>
    <clientes>
      <cliente>
        <codigoCliente>ABC-789</codigoCliente>
        <descripcionCliente>solvente</descripcionCliente>
        <numeroVivienda>4</numeroVivienda>
        <costeVivienda>200000€</costeVivienda>
        <resumenViviendas>Excelente estado</resumenViviendas>
        <plazoAltaHacienda>6</plazoAltaHacienda>
      </cliente>
      <cliente>
        <codigoCliente>XYZ-456</codigoCliente>
        <descripcionCliente>insolvente</descripcionCliente>
        <numeroVivienda>1</numeroVivienda>
        <costeVivienda>85000€</costeVivienda>
        <resumenViviendas>En mal estado</resumenViviendas>
        <plazoAltaHacienda>2</plazoAltaHacienda>
      </cliente>
    </clientes>
  </sede>
</gestoria>

=== Adrisito123/LMSGI/UD4/Actividad4/Actividad1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gestoria SYSTEM "Actividad1.dtd">
<gestoria>
    <sede>
        <codigoSede>A1234567</codigoSede>
        <nombreEmpleado>Adrian</nombreEmpleado>
        <fechaAlta>29-09-2020</fechaAlta>

        <clientes>
            <cliente>
                <codigoCliente>abc-123</codigoCliente>
                <descripcionCliente>solvente</descripcionCliente>
                <numeroVivienda>19</numeroVivienda>
                <costeVivienda>145000€</costeVivienda> 
                <resumenViviendas>Poducto muy fragil</resumenViviendas>
                <plazoAltaHacienda>12</plazoAltaHacienda>
            </cliente>
            <cliente>
                <codigoCliente>def-456</codigoCliente>
                <descripcionCliente>solvente</descripcionCliente>
                <numeroVivienda>2</numeroVivienda>
                <costeVivienda>45000€</costeVivienda> 
                <resumenViviendas>Poducto muy fragil</resumenViviendas>
                <plazoAltaHacienda>5</plazoAltaHacienda>
            </cliente>
        </clientes>
    </sede>
</gestoria>
